
# Workflow name
name: 'Build and Test'

# Event for the workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

# List of jobs
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 8.7.6
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build package
        run: pnpm build --filter=@arkejs/table
      #      - name: Test
      #        run: pnpm test --filter=@arkejs/table
      #      - name: Upload coverage reports to Codecov
      #        uses: codecov/codecov-action@v3
      - uses: chromaui/action@v1
        continue-on-error: true
        with:
          workingDir: './apps/storybook'
          debug: true
          exitOnceUploaded: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
